:toc:

# *Spring 5 REST API whiteapp*

Cette whiteapp à pour but de montrer comment créer une API Rest avec springboot 2 en séparant au maximum le technique du fonctionnel.

image::https://travis-ci.org/nduheron/spring-rest-api.svg?branch=master[link=https://travis-ci.org/nduheron/spring-rest-api]
image::https://codecov.io/gh/nduheron/spring-rest-api/branch/master/graphs/badge.svg?branch=master[link=https://codecov.io/github/nduheron/spring-rest-api?branch=master]

## *Fonctionnalités*

- Authentification https://jwt.io/introduction/[JWT] avec https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/[spring-security]
- Internationalisation
- JSR-303 Bean Validation API
- BDD avec https://cucumber.io/[Cucumber]
- Tests unitaire avec http://site.mockito.org/[Mockito]
- Documentation avec https://swagger.io/[Swagger]
- Monitoring avec Actuator
- La gestion des erreurs
- Mapping entité->DTO avec http://mapstruct.org/[Mapstruct]
- Versionning Base de données avec https://flywaydb.org/[Flyway]
- Versionning des APIs

## *Structure du projet*

* `fr.nduheron.poc.springrestapi.config` : Configuration de l'application
* `fr.nduheron.poc.springrestapi.security` : Lien entre spring-security et le métier lié aux utilisateurs
* `fr.nduheron.poc.springrestapi.tools.actuator` : Addons pour actuator (Nouveau endpoint pour la  gestion des caches, ajout d'actuator à la documentation Swagger, sécurisisation des endpoints)
* `fr.nduheron.poc.springrestapi.tools.exception` : Transforme les exceptions en réponse REST
* `fr.nduheron.poc.springrestapi.tools.log` : Log toutes les requêtes et réponses des appels REST
* `fr.nduheron.poc.springrestapi.tools.security` : Ajout de JWT à spring-security (filtre HTTP permettant de décoder le jeton JWT, configuration des URLs protégées, ajout des réponses 401 et 403 à la documentation Swagger quan nécessaire)
* `fr.nduheron.poc.springrestapi.tools.swagger` : Gestion automatique de la documentation swagger pour les erreurs
* `fr.nduheron.poc.springrestapi.user` : Contient toutes les classes métiers (Controller, DAO, POJO métier...)

## *Installation*

#### Prérequis

- Java 8
- Maven 3
- Docker

### Commandes

```bash
mvn docker:build docker:start
mvn package
java -jar spring-rest-api-0.0.1-SNAPSHOT.jar
```

## *Api*

include::docs/authentification/overview.adoc[leveloffset=+2]
include::docs/authentification/paths.adoc[leveloffset=+2]
include::docs/authentification/definitions.adoc[leveloffset=+2]

include::docs/user/overview.adoc[leveloffset=+2]
include::docs/user/paths.adoc[leveloffset=+2]
include::docs/user/definitions.adoc[leveloffset=+2]

include::docs/features.adoc[leveloffset=+1]