{
 "title": "System Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_exporter_build_info, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_exporter_build_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$instance\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$instance\",job=~\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "singlestat",
   "description": "Disk Space Used",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((sum(node_filesystem_avail_bytes{instance=~\"$instance\",job=~\"$job\",device!~'rootfs'}) * 100) / sum(node_filesystem_size_bytes{instance=~\"$instance\",job=~\"$job\",device!~'rootfs'}))"
    }
   ]
  },
  { "title": "CPU / Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  { "title": "Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\",job=~\"$job\"} [5m])",
     "legendFormat": "{{device}} - Milliseconds spent doing I/Os"
    }
   ]
  },
  {
   "title": "Open Error File",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "node_textfile_scrape_error{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Textfile scrape error (1 = true)"
    }
   ]
  },
  { "title": "System Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Context Switches / Interrupts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "irate(node_intr_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Interrupts Detail",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_interrupts_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{ type }} - {{ info }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Descriptors" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Maximum open file descriptors"
    },
    {
     "expr": "process_open_fds{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Time Syncronized Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "node_timex_sync_status{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no)"
    },
    {
     "expr": "node_timex_frequency_adjustment_ratio{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Local clock frequency adjustment"
    }
   ]
  },
  {
   "title": "Processes State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Processes in runnable state"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "TCP Connection States",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Compressed",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive compressed"
    },
    {
     "expr": "irate(node_network_transmit_compressed_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit compressed"
    }
   ]
  }
 ]
}