
[[_userdefinitions]]
== Definitions

[[_usercreateuser]]
=== CreateUser

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**email** +
__required__|**Length** : `0 - 128` +
**Example** : `"batman@yopmail.fr"`|string
|**enabled** +
__optional__|**Example** : `true`|boolean
|**login** +
__required__|**Length** : `2 - 20` +
**Example** : `"batman"`|string
|**nom** +
__required__|**Length** : `2 - 50` +
**Example** : `"Wayne"`|string
|**prenom** +
__required__|**Length** : `2 - 50` +
**Example** : `"Bruce"`|string
|**role** +
__required__|**Example** : `"string"`|enum (ADMIN, USER, SYSTEM)
|===


[[_usererror]]
=== Error

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**additionalsInformations** +
__optional__|propriétés additionnelles spécifiques +
**Example** : `"object"`|object
|**attribute** +
__optional__|nom de l'attribut source de l'erreur +
**Example** : `"string"`|string
|**code** +
__required__|le code de l'erreur +
**Example** : `"string"`|string
|**message** +
__required__|description de l'erreur +
**Example** : `"string"`|string
|===


[[_userupdateuser]]
=== UpdateUser

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**email** +
__required__|**Length** : `0 - 128` +
**Example** : `"batman@yopmail.fr"`|string
|**enabled** +
__optional__|**Example** : `true`|boolean
|**nom** +
__required__|**Length** : `2 - 50` +
**Example** : `"Wayne"`|string
|**prenom** +
__required__|**Length** : `2 - 50` +
**Example** : `"Bruce"`|string
|**role** +
__required__|**Example** : `"string"`|enum (ADMIN, USER, SYSTEM)
|===


[[_useruser]]
=== User

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**derniereConnexion** +
__optional__|**Example** : `"string"`|string (date-time)
|**email** +
__required__|**Length** : `0 - 128` +
**Example** : `"batman@yopmail.fr"`|string
|**enabled** +
__optional__|**Example** : `true`|boolean
|**login** +
__optional__|**Length** : `2 - 20` +
**Example** : `"batman"`|string
|**nom** +
__required__|**Length** : `2 - 50` +
**Example** : `"Wayne"`|string
|**prenom** +
__required__|**Length** : `2 - 50` +
**Example** : `"Bruce"`|string
|**role** +
__required__|**Example** : `"string"`|enum (ADMIN, USER, SYSTEM)
|===



