:toc: right
:backend: html
:doctitle: Limitations
:doctype: book
:icons: font
:!numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3
:revnumber: 0.0.1-SNAPSHOT
:hardbreaks:
:chapter-label: Chapter
:version-label: Version

= *Limitations*


[[account-operations, account operations]]
== *account operations*

=== Récupérer mon profil utilisateur sans être  connecté

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
When ::
I get account icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a UNAUTHORIZED response icon:thumbs-up[role="green",title="Passed"]
==========

=== Récupérer mon profil utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I get account icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a OK response icon:thumbs-up[role="green",title="Passed"]
And ::
my name is Bruce Wayne icon:thumbs-up[role="green",title="Passed"]
And ::
I am SYSTEM user icon:thumbs-up[role="green",title="Passed"]
==========

=== Modifier son mot de passe sans être connecté

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
When ::
I change 12345 password with 123456 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a UNAUTHORIZED response icon:thumbs-up[role="green",title="Passed"]
==========

=== Modifier son mot de passe

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I change 12345 password with 123456 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NO_CONTENT response icon:thumbs-up[role="green",title="Passed"]
==========

=== Modifier son mot de passe avec une erreur d'authentification'

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I change 123456 password with 123456 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

[[account-operations-version-2, account operations version 2]]
== *account operations version 2*

=== Modifier son mot de passe sans être connecté

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
version 2 icon:thumbs-up[role="green",title="Passed"]
When ::
I change 12345 password with 123456 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a UNAUTHORIZED response icon:thumbs-up[role="green",title="Passed"]
==========

=== Modifier son mot de passe

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
version 2 icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I change 12345 password with 123456 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NO_CONTENT response icon:thumbs-up[role="green",title="Passed"]
==========

=== Modifier son mot de passe avec une erreur d'authentification'

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
version 2 icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I change 123456 password with 123456 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

[[authentification-operations, authentification operations]]
== *authentification operations*

=== Login

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
When ::
I login with username x and password x icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a BAD_REQUEST response icon:thumbs-up[role="green",title="Passed"]
==========

=== Login

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
When ::
I login with username blackpanther and password 12345 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a UNAUTHORIZED response icon:thumbs-up[role="green",title="Passed"]
==========

=== Login

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
When ::
I login with username humantorch and password 12345 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a UNAUTHORIZED response icon:thumbs-up[role="green",title="Passed"]
==========

=== Login

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
When ::
I login with username invisiblegirl and password 123456 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a UNAUTHORIZED response icon:thumbs-up[role="green",title="Passed"]
==========

=== Login

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
When ::
I login with username invisiblegirl and password 12345 icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a OK response icon:thumbs-up[role="green",title="Passed"]
==========

[[users-operations, users operations]]
== *users operations*

=== l'administrateur peut rechercher des utilisateurs

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I get all users icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a OK response icon:thumbs-up[role="green",title="Passed"]
And ::
4 users found icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur système peut rechercher des utilisateurs

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I get all users icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a OK response icon:thumbs-up[role="green",title="Passed"]
And ::
4 users found icon:thumbs-up[role="green",title="Passed"]
==========

=== Un utilisateur lambda n'a pas le droit de rechercher des utilisateurs

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with invisiblegirl icon:thumbs-up[role="green",title="Passed"]
When ::
I get all users icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur système peut rechercher un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I search user invisiblegirl icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a OK response icon:thumbs-up[role="green",title="Passed"]
And ::
the user has name Jane Storm icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur peut rechercher un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I search user invisiblegirl icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a OK response icon:thumbs-up[role="green",title="Passed"]
And ::
the user has name Jane Storm icon:thumbs-up[role="green",title="Passed"]
==========

=== Un utilisateur lambda n'a pas le droit de rechercher un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with invisiblegirl icon:thumbs-up[role="green",title="Passed"]
When ::
I search user batman icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== Rechercher un utilisateur qui n'existe pas

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I search user blackpanther icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NOT_FOUND response icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur système n'a pas le droit de supprimer un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I delete user invisiblegirl icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur peut supprimer un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I delete user invisiblegirl icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NO_CONTENT response icon:thumbs-up[role="green",title="Passed"]
And ::
the user invisiblegirl is deleted icon:thumbs-up[role="green",title="Passed"]
==========

=== Un utilisateur lambda n'a pas le droit de supprimer un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with invisiblegirl icon:thumbs-up[role="green",title="Passed"]
When ::
I delete user batman icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== La suppression est idempotente

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I delete user invisiblegirl icon:thumbs-up[role="green",title="Passed"]
And ::
I delete user invisiblegirl icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NO_CONTENT response icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur système n'a pas le droit de créer un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I create ironman user icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur peut créer un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I create ironman user icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a CREATED response icon:thumbs-up[role="green",title="Passed"]
And ::
the user ironman is created icon:thumbs-up[role="green",title="Passed"]
And ::
email password is sent icon:thumbs-up[role="green",title="Passed"]
==========

=== Un utilisateur lambda n'a pas le droit de créer un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with invisiblegirl icon:thumbs-up[role="green",title="Passed"]
When ::
I create ironman user icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== Créer un utilisateur sans remplir les champs obligatoires

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I create empty user icon:thumbs-up[role="green",title="Passed"]
And ::
I get a BAD_REQUEST response icon:thumbs-up[role="green",title="Passed"]
And ::
I get 5 parameters in error icon:thumbs-up[role="green",title="Passed"]
==========

=== Créer un utilisateur déjà existant

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I create invisiblegirl user icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a BAD_REQUEST response icon:thumbs-up[role="green",title="Passed"]
And ::
I get a ALREADY_EXIST error icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur système n'a pas le droit de modifier un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I update batman with superman data icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur peut modifier un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I update batman with superman data icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NO_CONTENT response icon:thumbs-up[role="green",title="Passed"]
And ::
the user batman has name Clark Kent icon:thumbs-up[role="green",title="Passed"]
==========

=== Un utilisateur lambda n'a pas le droit de modifier un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with invisiblegirl icon:thumbs-up[role="green",title="Passed"]
When ::
I update batman with superman data icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== Modifier un utilisateur sans remplir les champs obligatoires

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I update batman with empty data icon:thumbs-up[role="green",title="Passed"]
And ::
I get a BAD_REQUEST response icon:thumbs-up[role="green",title="Passed"]
And ::
I get 4 parameters in error icon:thumbs-up[role="green",title="Passed"]
==========

=== Modifier un utilisateur qui n'existe pas

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I update blackpanther with superman data icon:thumbs-up[role="green",title="Passed"]
And ::
I get a NOT_FOUND response icon:thumbs-up[role="green",title="Passed"]
==========

l'administrateur système n'a pas le droit de réinitialiser le mot de passe d'un utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I reinit password to invisiblegirl icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur système peut réinitialiser son mot de passe

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with batman icon:thumbs-up[role="green",title="Passed"]
When ::
I reinit password to batman icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NO_CONTENT response icon:thumbs-up[role="green",title="Passed"]
And ::
the password to batman has changed icon:thumbs-up[role="green",title="Passed"]
And ::
email reinit password is sent icon:thumbs-up[role="green",title="Passed"]
==========

=== l'administrateur a le droit de réinitialiser le mot de passe de n'importe quel utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I reinit password to invisiblegirl icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NO_CONTENT response icon:thumbs-up[role="green",title="Passed"]
And ::
the password to invisiblegirl has changed icon:thumbs-up[role="green",title="Passed"]
And ::
email reinit password is sent icon:thumbs-up[role="green",title="Passed"]
==========

=== un utilisateur lambda n'a pas le droit de réinitialiser le mot de passe d'un autre utilisateur

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with invisiblegirl icon:thumbs-up[role="green",title="Passed"]
When ::
I reinit password to spiderman icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a FORBIDDEN response icon:thumbs-up[role="green",title="Passed"]
==========

=== un utilisateur lambda peut réinitialiser son mot de passe

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with invisiblegirl icon:thumbs-up[role="green",title="Passed"]
When ::
I reinit password to invisiblegirl icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NO_CONTENT response icon:thumbs-up[role="green",title="Passed"]
And ::
the password to invisiblegirl has changed icon:thumbs-up[role="green",title="Passed"]
And ::
email reinit password is sent icon:thumbs-up[role="green",title="Passed"]
==========

=== Réinitialiser le mot de passe d'un utilisateur qui n'existe pas

==========
Given ::
users datasets icon:thumbs-up[role="green",title="Passed"]
And ::
I login with spiderman icon:thumbs-up[role="green",title="Passed"]
When ::
I reinit password to superman icon:thumbs-up[role="green",title="Passed"]
Then ::
I get a NOT_FOUND response icon:thumbs-up[role="green",title="Passed"]
==========

